POST http://ec2-15-164-134-227.ap-northeast-2.compute.amazonaws.com:8000/detect
Content-Type: application/json

{
  "urls": ["https://t4.ftcdn.net/jpg/08/31/05/23/360_F_831052326_NkjqmsokAXYHWlIekbiPP5b55jHmjy6b.jpg"],
  "rate": 100,
  "requestUrl": "aaa",
  "type": 2
}